### ISSUE TITLE
ModuleNotFound error

### ISSUE THREAD

**Issue by Shambhujii** [UdbhavPrasad072300/Transformer-Implementations#3]
while i execute "from models.transformer import ViT" it generates error saying "No module named 'models"
I am using the latest version of Pytorch,,,what may be the cause for this type of error??
![Capture](https://user-images.githubusercontent.com/65452482/104633499-5507fe80-56c7-11eb-87e8-fbaaea1b4cda.PNG)

**Comment by UdbhavPrasad072300** [comment]
If you are using the files locally then you would use "from models.transformer import ViT". but if you are using from PyPi, then you want to specify the package name first.

On my machine, I installed these modules locally through "pip install -e .", so i wouldn't have to reinstall them after updates

**Comment by Shambhujii** [comment]
i am implementing this in Google Colab,,and facing the same issue "ModuleNotFoundError"

**Comment by UdbhavPrasad072300** [comment]
I'm working on a fix, I would recommend copying the model class and using it directly for now

**Comment by parth2035** [comment]
The issue has been fixed with version 0.0.7, and the module can now be imported with "from transformer_package.models import transformer"
